<?php

//Multi page (Local):
define('__Retour', 'Menu de navigation');
define('__Reset', 'Annuler');
define('__Valide','Valider');
define('__Supprimer','Supprimer');
define('__Modifier','Modifier');
define('__Fac', 'Facultatif');

//Page tournoi (Local):
define('__Titre_tournoi', 'Configuration du tournoi');
define('__Nom_tournoi', 'Nom du tournoi');
define('__Date_d', 'Date de debut');
define('__Date_f', 'Date fin');
define('__Type_t', 'Type de tournoi');
define('__Nbre_m', 'Nombre de manche');
define('__Nbre_to', 'Nombre de tour');
define('__Nbre_ta', 'Nombre de table');
define('__Table_t', 'Tournois enregistrés');
define('__Id_tournoi', 'Id tournoi');
define('__Id_configuration', 'Thème');

//Page modification tournoi (Local):
define('__Titre_modif_tournoi', 'Modification du tournoi');
define('__Retour_tournoi', 'Nouveau tournoi');

//Page tournoi, page configuration (Local):
define('__Choix_t', 'Choix du theme');

//Page configuraton (Local):
define('__Titre_configuration', 'Page thème');
define('__Ajout_t', 'Ajouter un nouveau thème');
define('__Table_co', 'Liste des thèmes');
define('__Id_co', 'Id thème');

//Poge modification configuration (Local):
define('__Titre_modif_configuration', 'Modification du des thèmes');
define('__Retour_parametre', 'Nouveau theme');

//Page parametre (Local):
define('__Titre_parametre', 'Ajout d\'un nouveau thème');
define('__Nom_p', 'Nom du thème');
define('__Cou_f', 'Couleur du Fond');
define('__Cou_t', 'Couleur du Texte');
define('__Taille', 'Taille de la police');
define('__Gras', 'Gras');
define('__Oui', 'Oui');
define('__Non', 'Non');
define('__Com_g', '0 pour NON, 1 pour OUI');
define('__Forme', 'Style de la police');
define('__Table_p', 'Parametres enregistrés');
define('__Id_parametre', 'Id parametre');

//Page de modification parametre (Local):
define('__Titre_modif_parametre', 'Modification des parametres');
define('__Retour_theme', 'Nouveau theme');

//Page tableau (Local):
define('__Titre_tableau', 'Configuration du tableau');
define('__Nom_tableau', 'Nom du tableau');
define('__Descriptif', 'Descriptif du tableau');
define('__Id_tableau', 'Id tableau');
define('__Table_ta', 'Tableau enregistrés');

//Page modification tableau (Local):
define('__Titre_modif_tableau', 'Modification du tableau');
define('__Retour_tableau', 'Nouveau tableau');

//Page tour (Local):
define('__Titre_tour', 'Horaire des tours');
define('__Num_t', ' Tour');
define('__Horaire', 'Horaire du tour');
define('__Id_tour', 'Id tour');
define('__Table_to', 'Horaire enregistrés');

//Page modification tour (Local):
define('__Titre_modif_tour', 'Modification de l\`horaire');
define('__Retour_tour', 'Nouveau tour');

//Page Rencontre (Local):
define('__Titre_rencontre', 'Configuration des rencontres');
define('__Table', 'Numero de la table');
define('__Sel_Comp1', 'Seletion du Competiteur 1');
define('__Sel_Comp2', 'Selection du Competiteur 2');
define('__Comp1', 'Competiteur 1');
define('__Comp2', 'Competiteur 2');
define('__Id_match', 'Id match');
define('__Table_r', 'Matchs enregistrés');
define('__Statut', 'Statut');

//Page modification de la rencontre (Local):
define('__Titre_modif_match', 'Modification de la rencontre');
define('__Retour_rencontre', 'Nouvelle rencontre ');

//Page Rencontre, Sponsor, Pub (Local):
define('__Act', 'Action');
define('__Sup_i', 'Supprimer');
define('__Upload','Telecharger');

//Page Sponsor (Local):
define('__Titre_sponsor', 'Configuration du sponsor');
define('__Liste_Sponsor', 'sponsor');

//Page Sponsor, Pub (Local):
define('__Nom_f', 'Nom du fichier à telecharger');
define('__Image', 'Apercu du sponsor');
define('__Nom_i', 'Nom de l\'image');

//Page Pub (Local):
define('__Titre_pub', 'Configuration des Publicités');
define('__Titre_publicite', 'Liste des pubs');

//Page Menu (Local):
define('__Titre_menu', 'Menu de navigation');
define('__Tournoi', 'Configuration du tournoi');
define('__Tableau', 'Configuration du tableau');
define('__Tour', 'Configuration horaire des tours');
define('__Rencontre', 'Configuration des rencontres');
define('__Sponsor', 'Configuration du bandeau (sponsor)');
define('__Pub', 'Configuration des Pubs');
define('__Theme', 'Configuration du thème');
define('__Competiteur', 'Configuration des compétiteurs');
define('__Match', 'Gestion des matchs');
define('__aff_all', 'Affichage de toutes les tables ');
define('__aff_table', 'Affichage 1 table');
define('__aff_pub', 'Affichage des pubs');
define('__Lien_admin', 'Liens de configuration');
define('__Lien', 'Liens pour les differents affichage');
define('__Lien_RAZ', 'Remise à zéro des bases ');
define('__Select_RAZ', 'Remise à zéro des bases ');


//Page competiteur (Local):
define('__Titre_competiteur', 'Ajout d\'un competiteur');
define('__Nom','Nom');
define('__Prenom','Prenom');
define('__Num_d','Numero du dossard');
define('__Sexe','Sexe');
define('__Cat_r','Catégorie réel du competiteur');
define('__Pays','Pays');
define('__BE','Belgique');
define('__BY','Bielorussie'); 
define('__BG','Bulgarie');
define('__CZ','République tchèque');
define('__DK','Danemark');
define('__DE','Allemagne');
define('__EE','Estonie');
define('__IE','Irlande');
define('__EL','Grèce');
define('__ES','Espagne');
define('__FR','France');
define('__HR','Croatie');
define('__IT','Italie');
define('__CY','Chypre');
define('__LV','Lettonie');
define('__LT','Lituanie');
define('__LU','Luxembourg');
define('__HU','Hongrie');
define('__MD','Moldavie');
define('__MT','Malte');
define('__NL','Pays-Bas');
define('__AT','Autriche');
define('__PL','Pologne');
define('__PT','Portugal'); 
define('__RO','Roumanie');
define('__RU','Russie');
define('__SI','Slovénie');
define('__SK','Slovaquie');
define('__FI','Finlande');
define('__SE','Suède');
define('__RS','Serbie');
define('__UK','Royaume-Uni');
define('__EN','Angleterre');
define('__IL','Israel');
define('__Rang','Rang');
define('__Sup_c','Page de suppression d\'un competiteur');
define('__Sup_r',' Supprimer');
define('__Table_c','Liste des competiteurs');
define('__Id_competiteur','Id competiteur');

// Page modification competiteur (Local):
define('__Titre_modif_competiteur', 'Modification du competiteur');
define('__Retour_competiteur','Nouveau competiteur');

//Page supprime competiteur (Local):
define('__Titre_sup_c', 'Page de suppression d\'un competiteur');
define('__Sel_c','Selectionner le competiteur à supprimer ');

//Affichage des pubs (Local):
define('__Titre_Aff_p', 'Pub');

//Affichage score all table (Local):
define('__Mess_all', 'En attente du match suivant');

//Affichage score table (Local):
define('__Mess_one', 'En attente du prochain match');

//Page match (Local):
define('__Titre_ma', 'Match ');
define('__Manche', 'Manche ');
define('__Faute', 'Faute ');
define('__Jaune', 'Carton Jaune');
define('__JR', 'Carton Jaune + Rouge (1)');
define('__JR2', 'Carton Jaune + Rouge (2)');
define('__WO', 'WO');
define('__TM', 'Temps Mort');
define('__Ret_se', 'Retour selection');
define('__Fin_m', 'Fin de match');
define('__Debut_m', 'Debut du match');
define('__Alert_fin', 'Confirmation de fin de match');
define('__Alert_false', 'Le match continu');

//Page de selection (Local):
define('__Dec', 'Retour accueil');

//Page de selection match table (Local):
define('__Titre_se_t', 'Selection de la table');

//accueil (Local):
define('__Utilisateur', 'Utilisateur');
define('__Paswword', 'Password');
define('__Titre_ac', 'Accueil');
define('__Annuler', 'Annuler');
define('__Valider', 'Valider');

//Page index (Local):
define('__Titre_start', 'Start');
define('__Valide_index', 'Entrer');
define('__Mes_index', 'Bienvenue sur l\'application de scoring en live');

//Page selection match admin (Local):
define('__Titre_se', 'Gestion de l\'affichage des tables');
define('__Titre_mat', 'Choix du match');
define('__Select', 'Selectionner');
define('__Table_sel_en_cour', 'Rencontres en cours');
define('__Table_sel_en_Att', 'Rencontres en attentes');
define('__Table_sel_fin', 'Rencontres finis');
define('__Table_sel_enr', 'Rencontres enregistrées');
define('__Table_sel_archive', 'Rencontres archivées');
define('__Action_att', 'En attente');
define('__Action_cours', 'En cours');
define('__Action_fin', 'Fini');
define('__Action_arch', 'Archivé');

//Page_menu_affichage (Publique):
define('__Aff_tour', 'Affichage de tous les matchs');
define('__Aff_match', 'Affichage d\'un seul match');
define('__Menu_affichage_', 'Menu');

//Page selection match cours (Publique):
define('__Retour_m', 'Retour au menu');
define('__Titre_menu_se', 'Sélectionner un match');
define('__valide_sel', 'Valider');

//Page RAZ (Local)
define('__Titre_RAZ', 'Remise à zéro des tables ');
define('__Alert_RAZ_base', 'Voulez-vous supprimer tout la base ?');
define('__Alert_RAZ_competiteur', 'Voulez-vous supprimer tout les competiteurs');
define('__Alert_RAZ_rencontre', 'Voulez-vous supprimer toute les rencontres');
define('__Alert_RAZ_tour', 'Voulez-vous supprimer tout les tours');
define('__Alert_RAZ_tableau', 'Voulez-vous supprimer tout les tableaux');
define('__Alert_RAZ_tournoi', 'Voulez-vous supprimer tout les tournois');
define('__mes10', 'RAZ de la base !');
define('__mes11', 'RAZ de la table tournoi !');
define('__mes12', 'La table tournoi est vide !');
define('__mes13', 'RAZ de la table tableau !');
define('__mes14', 'La table tableau est vide !');
define('__mes15', 'RAZ de la table tour !');
define('__mes16', 'La table tour est vide !');
define('__mes17', 'RAZ de la table competiteur !');
define('__mes18', 'La table competiteur est vide !');
define('__mes19', 'RAZ de la table matchs !');
define('__mes20', 'La table matchs est vide !');

//Message erreur  (Local)
define('__mes1', 'Ce tournoi existe déja !');
define('__mes2', 'Ce tableau existe déja pour ce tournoi !');
define('__mes3', 'Ce tour existe déja !');
define('__mes4', 'Ce compétiteur existe déja !');
define('__mes5', 'Impossible de modifier le thème par defaut !');
define('__mes6', 'Vous avez selectionné le même joueur !');
define('__mes7', 'Ce match existe déja !');
define('__mes8', 'La table est déja prise pour ce tour ou alors superieur au nombre de table du tournoi !');
define('__mes9', 'Un des joueurs est déja enregisté pour ce tour !');
define('__mes21', 'Attention, un bandeau par tounoi !');
define('__mes22', 'Erreur de deplacement !');
define('__mes23', 'Erreur image !');
define('__mes24', 'Impossible de supprimer le thème par defaut !');




